@startuml
skinparam groupInheritance 1

skinparam package<<Layout>> {
  borderColor Transparent
  backgroundColor Transparent
  fontColor Transparent
  stereotypeFontColor Transparent
  BorderThickness 10
}

namespace Perfils{
class DadesRepartidor
class DadesCuiner
class DadesClient
}

namespace Comanda {
class Ingredient
class Plat
class DadesComanda
}

namespace Xats {
 package p1 <<Layout>>{
class Xat
}
class Missatge
} 

namespace Usuari{
class DadesUsuariGeneral
}

DadesUsuariGeneral <|-down- DadesRepartidor
DadesUsuariGeneral <|-down- DadesCuiner
DadesUsuariGeneral <|-down- DadesClient
DadesRepartidor <|-down- DadesClient
DadesRepartidor <|-down- DadesCuiner

DadesComanda -- Xat

DadesCuiner "1" -down- "1.." Plat
DadesClient "1" --down-- "0..3" DadesComanda
DadesRepartidor "1" --down-- "0..*" DadesComanda
DadesCuiner "1" -- "0..*" DadesComanda
Plat "1.." -down-o "0..*" DadesComanda
Xat "1" *- "1..*" Missatge
Plat "1" *-- "1..*" Ingredient
@enduml