@startuml
skinparam groupInheritance 1
skinparam linetype ortho
skinparam packageStyle rectangle
skinparam shadowing false
skinparam nodesep 25
skinparam ranksep 60

skinparam package<<Layout>> {
  borderColor Transparent
  backgroundColor Transparent
  fontColor Transparent
  stereotypeFontColor Transparent
  BorderThickness 10
}


namespace Perfils{
enum GestorComptes {
+void getDadesPerfil(DadesUsuariGeneral u)
+void SetDisp(DadesCuiner c, bool disp)
+void SetHoraDisp(DadesCuiner c, Date h)
}
class DadesRepartidor

class DadesCuiner {
-plats[]: Plat
-disp: bool
+void AfegirPlat(Plat p)
+void getPlats(&Plat[])
+void getDades()
+void SetDisp(bool disp)
+void SetHoraDisp(Date h)
}

class DadesClient {

}

class DadesClient
class DadesUsuariGeneral {
-nom: String
+void getDadesPerfil()
}
interface InterfícieExternaCorreu
interface InterfícieExternaGPS
}

namespace Comanda {
 package p2 <<Layout>>{
enum GestorComandes {
+void valorarComanda(DadesComanda c, int valoracio)
+void mostrarIngredientsPlat(DadesComanda c, Plat p)
+void modificarIngredients(DadesComanda c, Plat p)
+void getDadesComandes()
+void getDadesComanda(DadesComanda c)
+void AcceptarComanda(DadesComanda c)
+void AcabarComanda(DadesComanda c)
+void RebutjarComanda(DadesComanda c)
}

class DadesComanda {
-nomClient: String
-nomCuiner: String
-preuTotal: float
-idComanda: String
-plats[]: Plat
-status: String
+String getNomClient()
+String getNomCuiner()
+float getPreuTotal()
+String getId()
+(String nom1, String nom2, float preu, String id) getDades()
+void AfegirPlat(Plat p)
+void getPlats(&Plat[])
+void AcceptarComanda()
+void AcabarComanda()
+void RebutjarComanda()
}

class DadesPagament
class DadesEnviament
}
interface InterfícieEnviaments {
+void modificarDataHora(data,hora)
+void dataErronea()
+void horaNoDisponible(horari)
+void modificacioCorrecte()
}
interface InterfícieExternaBanc
interface InterfícieComandes {
+void valorarComanda()
+void mostrarIngredientsPlat()
+void modificarIngredients()
+void PestanyaComandes()
+void MostrarReserves()
+void EntrarReserva(DadesComanda r)
+void MostrarReserva(DadesComanda r)
+void NotificarClient(String m, DadesComanda c=NULL)
+void AcceptarComanda()
+void AcabarComanda()
+void RebutjarComanda()
+void denegarValoracio()
+void puntuacioForaDeRang()
+void valoracioCorrecte()
+void mostrarIngredientsPlat(ingredients)
+void modificarIngredients(comanda,plat,ing)
+void denegarModificacio()
+void modificacioCorrecte()
+void escollirRepartidor()
+void repartidorAssignat(localitzacio)
+void comandesPendents()
+void veureInfoEnviament()
+void interactuaComanda()
}
}

namespace Menú {
package p4 <<Layout>>{

enum GestorPlat {
+Plat crearNouPlat(Cuiner c)
+void ConsultarNomsIguals(Plat p, String nom)
+void AfegirInformació(Plat p, String nom, String desc)
+void AfegirImatge(Plat p, Image img)
+void afegirIngredients(Plat p, (Ingredient ing, bool opcional)[])
+void getDadesPropostes()
+void getDadesPlat(Plat p)
+void AcceptarProposta(Plat p)
+void RebutjarProposta(Plat p, String m="")
}

}

class Plat {
-nom: String
-imgs[]: Image
-{field} ings[]: (Ingredient, bool)
-void getImgs(&Image[])
-preu: float
-esProposta: bool
+String getNom()
+plat(Cuiner c)
+void afegirIngredients((Ingredient ing, bool opcional)[])
+float getPreu()
+void setEsProposta(bool p)
+void AcceptarProposta()
+void RebutjarProposta()
}

class Ingredient {
-nom: String
-alèrgens[]: String
+(nom, alèrgens[]) getDades()
}

interface InterfícieMenuPrincipal {
+void PestanyaPerfil()
+void NotificarUsuari(String m)
+void MostrarPerfil()
+void IndicarDisponibilitat(bool disp)
+void IndicarHoraDisponible(Date h)
}

interface InterfíciePropostes {
+void NotificarClient(String notif, Plat p, String missatge="")
+void getDadesPropostes()
+void MostrarPropostes()
+void EntrarProposta()
+void MostrarProposta(Plat p)
+void AcceptarProposta()
+void RebutjarProposta()
+void AfegirMotiuRebuig(String motiu)
interface InterfícieMenuPrincipal {
+void iniciarComanda()
+void mostrarPlats(listP)
+void escollirPlats(plats)
+void maximComandesActives(nc)
+void comandaCreadaCorrectament(nc)
+void modificarCaracteristiques(c,data,hora,ingredients,repartidor)
+void comandaProcessadaCorrectament()
}

interface InterfíciePlat {
+void NotificarClient(String missatge)
+void crearNouPlat()
+void AfegirInformació(String nom, String desc)
+void AfegirImatge(Image img)
+void afegirIngredients((Ingredient ing, bool opcional)[])
}

}

namespace Xats {
 package p1 <<Layout>>{
class Xat {
-comandaID: String
-XatID: String
-missatges[]: Missatge
+(String nom1, String nom2, String XatID) getDades()
+String CrearNouMissatge()
+void UpdateMissatge(String mId, String txt)
+void adjuntarImatges(String mId, Image imgs[])
+void adjuntarMissatgeDeVeu(String mId, VoiceMessage vMsg)
+void afegirMissatge(String mId)
}

}
class Missatge {
-mId: String
-text: String
-imgs[]: Image
-voiceMsg: VoiceMessage
-status: String
+Missatge()
+String getID()
+void updateText(String txt)
+void adjuntarImatges(Image img[])
+void adjuntarMissatgeDeVeu(VoiceMessage vMsg)
+void setStatus(String status)
}

enum GestorXat {
+void GetXats()
+void GetDadesXat(x)
+String CrearNouMissatge(Xat x)
+void UpdateMissatge(Xat X, String mId, String txt)
+void adjuntarImatges(Xat X, String mId, Image imgs[])
+void adjuntarMissatgeDeVeu(Xat X, String mId, VoiceMessage vMsg)
+void enviarMissatge(Xat X, String mId)
+void enviarNotificació(String mId)
}

interface InterfícieXat {
+void NotificarClient(String missatge)
+void PestanyaXats()
+void MostrarXats(Xats[] xs)
+void MostrarXat(Xat x)
+void CrearNouMissatge()
+void UpdateMissatge(String txt)
+void adjuntarImatge(Image img)
+void adjuntarMissatgeDeVeu(VoiceMessage vMsg)
+void enviarMissatge()
+void enviat(String mId)
}

} 

InterfícieXat -right- GestorXat
InterfícieMenuPrincipal -- GestorComptes
InterfícieMenuPrincipal -- GestorPlat
InterfícieMenuPrincipal -- GestorComandes
InterfícieExternaCorreu -- GestorComptes
InterfícieExternaGPS -- GestorComptes
InterfíciePropostes -- GestorPlat
InterfíciePlat -- GestorPlat
InterfícieExternaBanc -- GestorComandes
InterfícieComandes -- GestorComandes
InterfícieEnviaments -- GestorComandes

DadesUsuariGeneral <|-down- DadesRepartidor
DadesUsuariGeneral <|-down- DadesCuiner
DadesUsuariGeneral <|-down- DadesClient

DadesComanda "1" -right- "1" DadesPagament
DadesComanda "1" -left- "1" DadesEnviament

DadesComanda -- Xat

DadesCuiner "1" -down- "1.." Plat
DadesClient "1" --down-- "    0..*" DadesComanda
DadesRepartidor "1" --down-- "0..*" DadesEnviament
DadesCuiner "1" -down- "          0..3" DadesComanda
Plat "1" -up-o "0..*" DadesComanda
Xat "   1" *- "1..*" Missatge
Plat "1" o-- "1..*" Ingredient

GestorComptes "1" -- "1..*" DadesUsuariGeneral
GestorComandes "1" -up- "1..*" DadesComanda
GestorPlat "     1" -left- "1..*" Plat
GestorXat "1" -up- "1..*" Xat
@enduml