@startuml
skinparam groupInheritance 1
skinparam linetype ortho
skinparam packageStyle rectangle
skinparam shadowing false
skinparam nodesep 25
skinparam ranksep 60

skinparam package<<Layout>> {
  borderColor Transparent
  backgroundColor Transparent
  fontColor Transparent
  stereotypeFontColor Transparent
  BorderThickness 10
}


namespace Perfils{
enum GestorComptes
class DadesRepartidor

class DadesCuiner {

}

class DadesClient {

}
class DadesUsuariGeneral {
-nom: String
+String getNom()
}
interface InterfícieExternaCorreu
interface InterfícieExternaGPS
}

namespace Comanda {
 package p2 <<Layout>>{
enum GestorComandes {
+void valorarComanda(DadesComanda c, int valoracio)
+void mostrarIngredientsPlat(DadesComanda c, Plat p)
+void modificarIngredients(DadesComanda c, Plat p)
}

class DadesComanda {
-nomClient: String
-nomCuiner: String
-preuTotal: float
-idComanda: String
+String getNomClient()
+String getNomCuiner()
+float getPreuTotal()
+String getId()
+(String nom1, String nom2, float preu, String id) getDades()
}

class DadesPagament
class DadesEnviament
}
interface InterfícieEnviaments
interface InterfícieExternaBanc
interface InterfícieComandes {
+void valorarComanda()
+void mostrarIngredientsPlat()
+void modificarIngredients()
}
}

namespace Menú {
package p4 <<Layout>>{

enum GestorPlat {
+Plat crearNouPlat(Cuiner c)
+void ConsultarNomsIguals(Plat p, String nom)
+void AfegirInformació(Plat p, String nom, String desc)
+void AfegirImatge(Plat p, Image img)
+void afegirIngredients(Plat p, (Ingredient ing, bool opcional)[])
}

}

class Plat {
-nom: String
-imgs[]: Image
-ings[]: (Ingredient, bool)
-void getImgs(&Image[])
-preu: float
+String getNom()
+plat(Cuiner c)
+void afegirIngredients((Ingredient ing, bool opcional)[])
+float getPreu()
}

class Ingredient {
-nom: String
-alèrgens[]: String
+(nom, alèrgens[]) getDades()
}

interface InterfícieMenuPrincipal
interface InterfíciePropostes

interface InterfíciePlat {
+void NotificarClient(String missatge)
+void crearNouPlat()
+void AfegirInformació(String nom, String desc)
+void AfegirImatge(Image img)
+void afegirIngredients((Ingredient ing, bool opcional)[])
}

}

namespace Xats {
 package p1 <<Layout>>{
class Xat {
-comandaID: String
-XatID: String
-missatges[]: Missatge
+(String nom1, String nom2, String XatID) getDades()
}

}
class Missatge

enum GestorXat {
+void GetXats()
+void GetDadesXat(x)
}

interface InterfícieXat {
+void NotificarClient(String missatge)
+void PestanyaXats()
+void MostrarXats(Xats[] xs)
+void MostrarXat(Xat x)
}

} 

InterfícieXat -right- GestorXat
InterfícieMenuPrincipal -- GestorComptes
InterfícieMenuPrincipal -- GestorPlat
InterfícieMenuPrincipal -- GestorComandes
InterfícieExternaCorreu -- GestorComptes
InterfícieExternaGPS -- GestorComptes
InterfíciePropostes -- GestorPlat
InterfíciePlat -- GestorPlat
InterfícieExternaBanc -- GestorComandes
InterfícieComandes -- GestorComandes
InterfícieEnviaments -- GestorComandes

DadesUsuariGeneral <|-down- DadesRepartidor
DadesUsuariGeneral <|-down- DadesCuiner
DadesUsuariGeneral <|-down- DadesClient

DadesComanda "1" -right- "1" DadesPagament
DadesComanda "1" -left- "1" DadesEnviament

DadesComanda -- Xat

DadesCuiner "1" -down- "1.." Plat
DadesClient "1" --down-- "    0..*" DadesComanda
DadesRepartidor "1" --down-- "0..*" DadesEnviament
DadesCuiner "1" -down- "          0..3" DadesComanda
Plat "1" -up-o "0..*" DadesComanda
Xat "   1" *- "1..*" Missatge
Plat "1" o-- "1..*" Ingredient

GestorComptes "1" -- "1..*" DadesUsuariGeneral
GestorComandes "1" -up- "1..*" DadesComanda
GestorPlat "     1" -left- "1..*" Plat
GestorXat "1" -up- "1..*" Xat
@enduml