@startuml

actor Usuari
note over Usuari: L'usuari pot ser Client o Cuiner.
boundary InterfícieXat
control GestorXat
entity Xat
entity DadesComanda

Usuari -> InterfícieXat++: PestanyaXats()
InterfícieXat -> GestorXat--++: GetXats()
loop
GestorXat->Xat++: GetDades()
Xat->DadesComanda: GetDades()
DadesComanda-->Xat--
Xat-->GestorXat--
end
alt Hi ha xats actius
GestorXat->InterfícieXat--: MostrarXats() 

opt Entrar a Xat
Usuari -> InterfícieXat++: EntrarXat(x)
InterfícieXat -> GestorXat--++: GetDadesXat(x)
GestorXat->Xat++: GetDadesXat()
Xat->DadesComanda: GetDadesComanda()
DadesComanda-->Xat--
Xat-->GestorXat--
GestorXat->InterfícieXat--: MostrarXat(x) 
end

else No hi ha xats actius
GestorXat->InterfícieXat: NotificarClient("Error: “No hi ha xats actius")
end

@enduml