@startuml
skinparam groupInheritance 1
skinparam linetype ortho
skinparam packageStyle rectangle
skinparam shadowing false
skinparam nodesep 25
skinparam ranksep 60

skinparam package<<Layout>> {
  borderColor Transparent
  backgroundColor Transparent
  fontColor Transparent
  stereotypeFontColor Transparent
  BorderThickness 10
}


namespace Perfils{
class GestorComptes
class DadesRepartidor
class DadesCuiner
class DadesClient
class DadesUsuariGeneral
interface InterfícieExternaCorreu
interface InterfícieExternaGPS
}

namespace Comanda {
 package p2 <<Layout>>{
class GestorComandes
class DadesComanda
class DadesPagament
class DadesEnviament
}
interface InterfícieEnviaments
interface InterfícieExternaBanc
interface InterfícieComandes
}

namespace Menú {
package p4 <<Layout>>{
class GestorPlat
}
class Plat
class Ingredient
interface InterfícieMenuPrincipal
interface InterfíciePropostes
interface InterfíciePlat
}

namespace Xats {
 package p1 <<Layout>>{
class Xat
}
class Missatge
class GestorXat
interface InterfícieXat
} 

InterfícieXat -right- GestorXat
InterfícieMenuPrincipal -- GestorComptes
InterfícieMenuPrincipal -- GestorPlat
InterfícieMenuPrincipal -- GestorComandes
InterfícieExternaCorreu -- GestorComptes
InterfícieExternaGPS -- GestorComptes
InterfíciePropostes -- GestorPlat
InterfíciePlat -- GestorPlat
InterfícieExternaBanc -- GestorComandes
InterfícieComandes -- GestorComandes
InterfícieEnviaments -- GestorComandes

DadesUsuariGeneral <|-down- DadesRepartidor
DadesUsuariGeneral <|-down- DadesCuiner
DadesUsuariGeneral <|-down- DadesClient

DadesComanda "1" -right- "1" DadesPagament
DadesComanda "1" -left- "1" DadesEnviament

DadesComanda -- Xat

DadesCuiner "1" -down- "1.." Plat
DadesClient "1" --down-- "    0..*" DadesComanda
DadesRepartidor "1" --down-- "0..*" DadesEnviament
DadesCuiner "1" -down- "          0..3" DadesComanda
Plat "1" -up-o "0..*" DadesComanda
Xat "   1" *- "1..*" Missatge
Plat "1" o-- "1..*" Ingredient

GestorComptes "1" -- "1..*" DadesUsuariGeneral
GestorComandes "1" -up- "1..*" DadesComanda
GestorPlat "     1" -left- "1..*" Plat
GestorXat "1" -up- "1..*" Xat
@enduml