@startuml
actor Client
boundary InterfícieComandes
control GestorComandes
entity DadesComanda

Client++
Client -> InterfícieComandes++: ConsultarComandesPrèvies()
Client--

InterfícieComandes -> GestorComandes ++: GetComandesPrèvies()
loop per totes les comandes
GestorComandes -> DadesComanda ++: GetDades()
DadesComanda --> GestorComandes --
end loop
alt Alguna comanda ha estat realitzada abans
GestorComandes->InterfícieComandes: MostrarComandesPrèvies() 
else No s'ha fet mai cap comanda
GestorComandes->InterfícieComandes--: NotificarClient("Error: “Mai s'ha fet cap comanda")
end


InterfícieComandes--

@enduml