@startuml
actor Client
boundary InterfícieComandes
control GestorComandes
entity DadesComanda

Client++
Client -> InterfícieComandes++: ConsultarComandesPrèvies()
InterfícieComandes -> GestorComandes++: GetNComandes()
alt Alguna comanda ha estat realitzada abans
GestorComandes->InterfícieComandes: MostrarComandesPrèvies() 
else No s'ha fet mai cap comanda
GestorComandes->InterfícieComandes--: NotificarClient("Error: “Mai s'ha fet cap comanda")
end

Client -> InterfícieComandes: VeureComandesPrèvies()
InterfícieComandes -> GestorComandes ++: VeureComandesPrèvies()
Client--
GestorComandes -> DadesComanda ++: GetDades()
DadesComanda --> GestorComandes --
GestorComandes --> InterfícieComandes--:
InterfícieComandes--

@enduml