@startuml

actor Client
boundary InterfícieComandes

control GestorComandes
entity DadesComanda

entity DadesClient

boundary InterfícieExternaBanc
actor EntitatBancària



Client -> InterfícieComandes++:FerPagament(comanda)
Client++
Client--
InterfícieComandes -> GestorComandes++:getImport(comanda)
GestorComandes -> DadesComanda++:getImport()
DadesComanda -> GestorComandes--
GestorComandes -> InterfícieComandes--: MostrarImport(import)



'InterfícieComandes->GestorComptes++:FerPagament(import,client)
InterfícieComandes->GestorComandes++:EfectuarTransferència(comanda, import)
GestorComandes->DadesComanda++:getDataClient()

DadesComanda->DadesClient++:getDataClient()
DadesClient-->DadesComanda--
DadesComanda-->GestorComandes--

GestorComandes->InterfícieExternaBanc++:EfectuarTransferència(compte_bancari)

EntitatBancària --> InterfícieExternaBanc:Acceptar/RebutjarTransferència()
EntitatBancària++
EntitatBancària--
InterfícieExternaBanc-->GestorComandes--
alt Si l'entiat bancària no realitza la transferència
GestorComandes -> InterfícieComandes: NotificarClient("Error: no s'ha pogut efectuar la transferència")
else l'entiat bancària ha relaitzat amv èxit la transferència
GestorComandes ->InterfícieComandes--:NotificarClient("S'ha efectuar la transferència")
InterfícieComandes--
end





@enduml