@startuml

actor Client
actor Cuiner

boundary InterfícieMenuPrincipal
control GestorComptes
entity DadesCuiner

control GestorPlat
boundary InterfíciePropostes
boundary InterfíciePlat
entity DadesPlat
entity DadesIngredient
entity DadesComanda
boundary InterfícieComandes

Client->InterfícieMenuPrincipal++:MostrarCuiners()
Client++
InterfícieMenuPrincipal -> GestorComptes++:getCuinersDisponibles()
GestorComptes->DadesCuiner++:getData()
DadesCuiner-->GestorComptes--
alt Hi ha cuiners disponibles
GestorComptes->InterfícieMenuPrincipal:MostrarCuinersDisponibles()

else No hi ha cuiners disponibles
GestorComptes->InterfícieMenuPrincipal: NotificarClient("No hi ha cuiners disponibles")
end

Client->InterfícieMenuPrincipal:SeleccionarCuiner()
InterfícieMenuPrincipal-->GestorComptes:SeleccionarCuiner(int id)


DadesCuiner--
GestorComptes-->InterfícieMenuPrincipal--

InterfícieMenuPrincipal->GestorPlat++:ProposarPlat(DadesCuiner cuiner)
InterfícieMenuPrincipal--

GestorPlat->InterfíciePropostes++:NovaProposta()
InterfíciePropostes->InterfíciePlat++:NouPlat()
InterfíciePlat-->InterfíciePropostes
InterfíciePlat--

GestorPlat->DadesPlat++: crearNouPlat(Cuiner c)
loop Per cada ingredient que es vulgui
DadesPlat->DadesIngredient++:AfegirIngredient()
DadesIngredient-->DadesPlat--
end
DadesPlat-->GestorPlat
GestorPlat--
DadesPlat--
Client->InterfíciePropostes:EnviarProposta()
Client--
InterfíciePropostes->GestorPlat++:EnviarProposta()
GestorPlat->DadesComanda++:FerComanda()
GestorPlat--
DadesComanda--
ref over DadesComanda,GestorPlat: CU Fer Comanda

Cuiner->InterfícieComandes++:AcceptarProposta()
Cuiner++
Cuiner--

InterfícieComandes--
ref over Cuiner, InterfícieComandes: AcceptarPropostes de plats

alt Si el cuiner ha acceptat la proposta
InterfíciePropostes->Client++:NotificarClient("El cuiner ha accpetat la proposta")
else Si no
InterfíciePropostes->Client--:NotificarClient("El cuiner ha rebutjat la proposta")
Client--


@enduml