@startuml

actor Usuari
boundary InterfícieComandes
control GestorComandes
entity DadesComanda

ref over Usuari,InterfícieComandes,GestorComandes,DadesComanda: CU Consultar Comandes Prèvies
loop
note over InterfícieComandes: El loop gran es fa tants cops com el client vulgui repetir una comanda,\n (respectant el límit de 3 comandes actives)

Usuari -> InterfícieComandes++: RepetirComanda(c)
InterfícieComandes -> GestorComandes--++: RepetirComanda(c)
GestorComandes -> DadesComanda : FerComanda()
ref over DadesComanda : CU Fer Comandes
'DadesComanda -> GestorComandes --: 

GestorComandes -> InterfícieComandes--: NotificaClient("S'ha repetit la comanda")
end