@startuml

actor Client
boundary InterfícieComandes
boundary InterfícieGPS
control GestorComandes
control GestorComptes

entity DadesComanda
entity DadesEnviament
entity DadesRepartidor
boundary InterfícieGPS

Client++
Client -> InterfícieComandes++: MostrarComandesActives()
InterfícieComandes -> GestorComandes--++: ConsultarComandesActives()

GestorComandes->DadesComanda++:GetDadesSiNoActiva()
DadesComanda-->GestorComandes--

alt Hi ha comandes actives
GestorComandes->InterfícieComandes: MostrarComandesActives() 
else No hi ha comandes actives
GestorComandes->InterfícieComandes--: NotificarClient("Error: “No hi ha comandes actives")
end

Client -> InterfícieComandes++: MostrarUbicacióComandaEspecífica()
Client--
InterfícieComandes -> GestorComandes++: MostrarUbicacióComandaEspecífica(c)
GestorComandes -> DadesComanda++: GetData(c)
DadesComanda -> DadesEnviament++: GetUbication(c)
DadesComanda --> GestorComandes
GestorComandes--

alt La comanda s'està repartint
DadesEnviament->DadesRepartidor++: getUbicacio()
DadesRepartidor-->DadesEnviament--

DadesEnviament-->DadesComanda--
DadesComanda->GestorComptes++: getUbicacio()
DadesComanda--
GestorComptes->InterfícieGPS++: getUbicacio()
InterfícieGPS-->GestorComptes
InterfícieGPS--
GestorComptes--



else La comanda no s'està repartint
GestorComandes->InterfícieComandes: NotificarClient("Error: “No s'està repartint la comanda")

GestorComandes++
InterfícieComandes--
GestorComandes--
end




@enduml