@startuml

actor Usuari
boundary InterfícieComandes
boundary InterfícieGPS
boundary InterfícieGPS
control GestorComandes
control GestorComptes

entity DadesComanda
entity DadesEnviament
entity DadesRepartidor


Usuari -> InterfícieComandes++: MostrarComandesActives()
InterfícieComandes -> GestorComandes--++: ConsultarComandesActives()
alt Hi ha comandes actives
GestorComandes->InterfícieComandes--: MostrarComandesActives() 
else No hi ha comandes actives
GestorComandes->InterfícieComandes: NotificarClient("Error: “No hi ha comandes actives")
end

Usuari -> InterfícieComandes++: MostrarUbicacióComandaEspecífica()
InterfícieComandes -> GestorComandes++: MostrarUbicacióComandaEspecífica(c)
GestorComandes -> DadesComanda++: GetData(c)
DadesComanda -> DadesEnviament++: GetUbication(c)
DadesEnviament --> DadesComanda
DadesComanda --> GestorComandes

alt La comanda s'està repartint
DadesEnviament->DadesRepartidor++: getUbicacio()
DadesRepartidor->GestorComptes++: getUbicacio()
GestorComptes->InterfícieGPS++: getUbicacio()

'aaa



else La comanda no s'està repartint
GestorComandes->InterfícieComandes: NotificarClient("Error: “No s'està repartint la comanda")
end




@enduml