@startuml

actor UsuariGeneral
boundary InterfícieMenuPrincipal
boundary InterfícieExternaBanc

control GestorComptes
entity DadesUsuariGeneral 
'estaria be fer ref a la generalitzacio?


UsuariGeneral -> InterfícieMenuPrincipal++: VincularCompteBancari()
UsuariGeneral++
InterfícieMenuPrincipal -> GestorComptes++: VincularCompteBancari()
InterfícieMenuPrincipal--
GestorComptes -> DadesUsuariGeneral++: GetData()
DadesUsuariGeneral --> GestorComptes

alt El compte té NIF vinculat
GestorComptes->InterfícieExternaBanc--: MostrarMenuIntroudïrIban()
else El compte no té NIF vinculat
GestorComptes->InterfícieMenuPrincipal--: NotificarClient("Error: “No hi ha NIF associat al compte, l'operació es cancela.")
end



loop Fins que IBAN sigui vàlid
UsuariGeneral -> InterfícieExternaBanc++: IntroduïrIBAN(i)
UsuariGeneral--
InterfícieExternaBanc -> GestorComptes++: IntroduïrIBAN(i)
alt el IBAN és vàlid

GestorComptes -> DadesUsuariGeneral: ModificarIBAN(i)
DadesUsuariGeneral--
GestorComptes -> InterfícieExternaBanc: NotificaUsuari("El IBAN ha estat modificat.")
else
GestorComptes -> InterfícieExternaBanc--: NotificaUsuari("El IBAN no és vàlid.")
InterfícieExternaBanc--
end
end 




@enduml