@startuml

actor Client
boundary InterfícieMenuPrincipal
control GestorComandes
control GestorPlat
entity Plat
entity Ingredient
entity DadesComanda

Client -> InterfícieMenuPrincipal: iniciarComanda()
InterfícieMenuPrincipal -> GestorComandes: getLlistaPlats()
GestorComandes -> GestorPlat: listP = getLlistaPlats()
loop
GestorPlat -> Plat: listP = getInfo()
loop
Plat -> Ingredient: listI = getInfo()
end
end
GestorComandes -> InterfícieMenuPrincipal: mostrarPlats(listP)
Client -> InterfícieMenuPrincipal: escollirPlats()
InterfícieMenuPrincipal -> GestorComandes: crearComanda(plats)
GestorComandes -> GestorComandes: nc = getNComandesActives()

alt Màxim comandes actives
GestorComandes -> InterfícieMenuPrincipal: maximComandesActives(nc)

else Dins del limit
GestorComandes -> DadesComanda: c = crearComanda(plats)
GestorComandes -> InterfícieMenuPrincipal: comandaCreadaCorrectament(nc)
Client -> InterfícieMenuPrincipal: modificarCaracteristiques()
InterfícieMenuPrincipal -> GestorComandes: modificarCaracteristiques(c,data,hora,ingredients,repartidor)
GestorComandes -> DadesComanda: modificarCaracteristiques(data,hora,ingredients,repartidor))

GestorComandes -> GestorComandes: ce = getCostEnviament(c)
GestorComandes -> DadesComanda: setCostEnviament(ce)
GestorComandes -> DadesComanda: calculaPreuFinal()

GestorComandes -> GestorComandes: comandaPendentPagament(c)
GestorComandes -> InterfícieMenuPrincipal: comandaProcessadaCorrectament()
end

@enduml