@startuml

actor Client
boundary InterfícieComandes
control GestorComandes
entity DadesComanda
entity Plat
entity Ingredients


Client -> InterfícieComandes: mostrarIngredientsPlat()
InterfícieComandes -> GestorComandes: mostrarIngredientsPlat(comanda,plat)

GestorComandes -> DadesComanda: ingredients = getIngredients(plat)
DadesComanda -> Plat: ingredients = getIngredients()
loop
Plat -> Ingredients: ingredients = getIngredient()
end

GestorComandes -> InterfícieComandes: mostrarIngredientsPlat(ingredients)
Client -> InterfícieComandes: modificarIngredients()
InterfícieComandes -> GestorComandes: modificarIngredients(comanda,plat,ing)

alt Modificació d'ingredient obligatori
GestorComandes -> InterfícieComandes: denegarModificació()

else Modificació acceptada
GestorComandes -> DadesComanda: modificarPlat(plat,ing)
DadesComanda -> Plat: modificarIngredients(ing)
loop
Plat -> Ingredients: setIngredient(i)
end
GestorComandes -> InterfícieComandes: modificacióCorrecte()
end


@enduml