@startuml

actor Usuari_General as Usuari
boundary InterficieMenuPrincipal as interficie
control gestor_comptes as gestor
entity DadesUsuariGeneral as dades

ref over Usuari : CU Registrar-se
Usuari -> interficie ++: 1.1 confirmar_registre(contr, correu)
interficie -> gestor --++: 1.2 confirmar_registre(contr, correu)
gestor -> dades : 1.3 guardar_dades(contr, correu)
gestor -> interficie--: 1.4 mostrar_opcions_omplir()

Usuari -> interficie ++: 2.1 omplir_dades(dades)
interficie -> gestor --++: 2.2 omplir_dades(dades)
alt no s'han omplert les dades obligatories
gestor -> interficie : 2.alt NotificaError(errorOmplirPerfil)
note over interficie : torna a 2.1
end
gestor -> dades : guardar_dades_perfil(dades)
gestor -> interficie --: 2.3 missatgeConfimacio(OmplirPerfil)

@enduml